upd

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,13 +45,19 @@ jobs:
     - name: Test
       run: |
         dotnet tool install -g dotnet-reportgenerator-globaltool --ignore-failed-sources
-        dotnet test --no-restore --verbosity normal --results-directory="${TESTRESULTS_DIRECTORY}" --collect:"XPlat Code Coverage${CI_DOTNET_TEST_COLLECTOR_OPT}" --nologo || (true && echo "ERROR test failure" >> errors)
-        reportgenerator -reports:${TESTRESULTS_DIRECTORY}/**/coverage.cobertura.xml '-reporttypes:TextSummary;JsonSummary' -targetdir:${TESTRESULTS_DIRECTORY}/CoverageReports
+        dotnet test --no-restore --verbosity normal --results-directory="${TESTRESULTS_DIRECTORY}" --logger:trx --collect:"XPlat Code Coverage${CI_DOTNET_TEST_COLLECTOR_OPT}" --nologo || (true && echo "ERROR test failure" >> errors)
+        reportgenerator -reports:${TESTRESULTS_DIRECTORY}/**/coverage.cobertura.xml '-reporttypes:TextSummary' -targetdir:${TESTRESULTS_DIRECTORY}/CoverageReports
         printf 'TEST_TOTAL_COVERAGE: ' &&  grep 'Line coverage:' ${TESTRESULTS_DIRECTORY}/CoverageReports/Summary.txt | awk -F': ' '{print $2}'
         if [ -e errors ] ; then cat errors ; exit 1 ; fi
+
+    - name: Run codacy-coverage-reporter
+      uses: codacy/codacy-coverage-reporter-action@v1.3.0
+      with:
+        project-token: ${{ secrets.CODACY_API_TOKEN }}
+        coverage-reports: ${{ env.TESTRESULTS_DIRECTORY }}/**/*cobertura.xml
         
-    - name: Archive coverage report
+    - name: Archive test report
       uses: actions/upload-artifact@v4
       with:
-          name: code-coverage-report
-          path: ${{ env.TESTRESULTS_DIRECTORY }}/CoverageReports/*.*
+          name: test-report
+          path: ${{ env.TESTRESULTS_DIRECTORY }}/**/*.*
